<?xml version="1.0" encoding="utf-8"?>
<sml Version="2.3.6" Modified="2012-09-22T10:39:51" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.suunto.com/schemas/sml">
    <DeviceLog>
        <Header>
            <Duration>1.9</Duration>
            <Ascent>0</Ascent>
            <Descent>0</Descent>
            <AscentTime>0</AscentTime>
            <DescentTime>0</DescentTime>
            <RecoveryTime>0</RecoveryTime>
            <Speed>
                <MaxTime>0</MaxTime>
            </Speed>
            <Cadence>
                <MaxTime>0</MaxTime>
            </Cadence>
            <ActivityType>3</ActivityType>
            <Activity>Running</Activity>
            <Temperature>
                <Max>301.35</Max>
                <Min>301.35</Min>
                <MaxTime>0</MaxTime>
                <MinTime>0</MinTime>
            </Temperature>
            <Distance>0</Distance>
            <LogItemCount>13</LogItemCount>
            <TimeToFirstFix>0</TimeToFirstFix>
            <BatteryChargeAtStart>0</BatteryChargeAtStart>
            <BatteryCharge>0</BatteryCharge>
            <DistanceBeforeCalibrationChange>0</DistanceBeforeCalibrationChange>
            <DateTime>2015-07-24T15:14:16</DateTime>
        </Header>
        <Samples>
            <Sample>
                <UTC>2015-07-24T15:14:16</UTC>
                <Time>0</Time>
                <Events>
                    <Pause>
                        <Type>31</Type>
                        <Duration>0</Duration>
                        <Distance>0</Distance>
                        <State>False</State>
                    </Pause>
                </Events>
            </Sample>
            <Sample>
                <Time>0</Time>
                <Events>
                    <Activity>
                        <CustomModeId>42098</CustomModeId>
                        <Type>Run</Type>
                    </Activity>
                </Events>
            </Sample>
            <Sample>
                <VerticalSpeed>0</VerticalSpeed>
                <Temperature>301.35</Temperature>
                <SeaLevelPressure>101330</SeaLevelPressure>
                <Speed>0</Speed>
                <Time>0.008</Time>
                <SampleType>periodic</SampleType>
            </Sample>
            <Sample>
                <VerticalSpeed>0</VerticalSpeed>
                <Temperature>301.35</Temperature>
                <SeaLevelPressure>101330</SeaLevelPressure>
                <Speed>0</Speed>
                <Time>0.008999999999999999</Time>
                <SampleType>periodic</SampleType>
            </Sample>
            <Sample>
                <Time>0.6960000000000001</Time>
                <Events>
                    <Cadence>
                        <Source>Wrist</Source>
                    </Cadence>
                </Events>
            </Sample>
            <Sample>
                <VerticalSpeed>0</VerticalSpeed>
                <Cadence>0</Cadence>
                <Temperature>301.35</Temperature>
                <SeaLevelPressure>101330</SeaLevelPressure>
                <Altitude>206</Altitude>
                <Speed>0</Speed>
                <Time>0.975</Time>
                <SampleType>periodic</SampleType>
            </Sample>
            <Sample>
                <VerticalSpeed>0</VerticalSpeed>
                <Cadence>0</Cadence>
                <Temperature>301.35</Temperature>
                <SeaLevelPressure>101330</SeaLevelPressure>
                <Altitude>206</Altitude>
                <Speed>0</Speed>
                <Time>1.631</Time>
                <SampleType>periodic</SampleType>
            </Sample>
            <Sample>
                <UTC>2015-07-24T15:14:16</UTC>
                <Time>1.636</Time>
                <Events>
                    <Pause>
                        <Type>30</Type>
                        <Duration>1.9</Duration>
                        <Distance>0</Distance>
                        <State>True</State>
                    </Pause>
                </Events>
            </Sample>
            <Sample>
                <VerticalSpeed>0</VerticalSpeed>
                <Cadence>0</Cadence>
                <Temperature>301.35</Temperature>
                <SeaLevelPressure>101330</SeaLevelPressure>
                <Altitude>206</Altitude>
                <Speed>0</Speed>
                <Time>1.638</Time>
                <SampleType>periodic</SampleType>
            </Sample>
            <Sample>
                <VerticalSpeed>0</VerticalSpeed>
                <Cadence>0</Cadence>
                <Temperature>301.35</Temperature>
                <SeaLevelPressure>101330</SeaLevelPressure>
                <Altitude>207</Altitude>
                <Speed>0</Speed>
                <Time>5.504</Time>
                <SampleType>periodic</SampleType>
            </Sample>
        </Samples>
    </DeviceLog>
</sml>
